[package]
name = "lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
audio = "0.2.0"
macroquad = "0.4.8"
once_cell = "1.19.0"
